# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riddler/protobuf/content_definition.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riddler.protobuf.ContentDefinition" do
    optional :id, :string, 1
    optional :created_at, :message, 2, "google.protobuf.Timestamp"
    optional :content_type, :enum, 3, "riddler.protobuf.ContentType"
    optional :content_id, :string, 4
    optional :version, :int32, 5
    optional :title, :string, 6
    optional :description, :string, 7
    optional :definition_schema_version, :int32, 8
    optional :definition, :string, 9
  end
  add_enum "riddler.protobuf.ContentType" do
    value :UNKNOWN_CONTENT_TYPE, 0
    value :STEP, 1
    value :ELEMENT, 2
  end
end

module Riddler
  module Protobuf
    ContentDefinition = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.ContentDefinition").msgclass
    ContentType = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.ContentType").enummodule
  end
end
