# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riddler/protobuf/content_management.proto

require 'google/protobuf'

require 'riddler/protobuf/definition_pb'
require 'riddler/protobuf/slug_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riddler.protobuf.CreateDefinitionRequest" do
    optional :definition, :message, 1, "riddler.protobuf.Definition"
  end
  add_message "riddler.protobuf.CreateDefinitionResponse" do
  end
  add_message "riddler.protobuf.CreateSlugRequest" do
    optional :slug, :message, 1, "riddler.protobuf.Slug"
  end
  add_message "riddler.protobuf.CreateSlugResponse" do
  end
  add_message "riddler.protobuf.UpdateSlugRequest" do
    optional :slug, :message, 1, "riddler.protobuf.Slug"
  end
  add_message "riddler.protobuf.UpdateSlugResponse" do
  end
end

module Riddler
  module Protobuf
    CreateDefinitionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateDefinitionRequest").msgclass
    CreateDefinitionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateDefinitionResponse").msgclass
    CreateSlugRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateSlugRequest").msgclass
    CreateSlugResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateSlugResponse").msgclass
    UpdateSlugRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.UpdateSlugRequest").msgclass
    UpdateSlugResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.UpdateSlugResponse").msgclass
  end
end
