# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riddler/protobuf/content_management.proto

require 'google/protobuf'

require 'riddler/protobuf/content_definition_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riddler.protobuf.CreateContentDefinitionRequest" do
    optional :content_definition, :message, 1, "riddler.protobuf.ContentDefinition"
  end
  add_message "riddler.protobuf.CreateContentDefinitionResponse" do
  end
end

module Riddler
  module Protobuf
    CreateContentDefinitionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateContentDefinitionRequest").msgclass
    CreateContentDefinitionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateContentDefinitionResponse").msgclass
  end
end
