# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riddler/protobuf/content_definition.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riddler.protobuf.ContentDefinition" do
    optional :id, :string, 1
    optional :created_at, :message, 2, "google.protobuf.Timestamp"
    optional :content_type, :string, 3
    optional :content_id, :string, 4
    optional :title, :string, 5
    optional :version, :int32, 6
    optional :schema_version, :int32, 7
    optional :definition_json, :string, 8
  end
end

module Riddler
  module Protobuf
    ContentDefinition = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.ContentDefinition").msgclass
  end
end
