# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riddler/protobuf/definition.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riddler.protobuf.Definition" do
    optional :id, :string, 1
    optional :created_at, :message, 2, "google.protobuf.Timestamp"
    optional :updated_at, :message, 3, "google.protobuf.Timestamp"
    optional :schema_version, :int32, 4
    optional :content_type, :string, 5
    optional :content_id, :string, 6
    optional :version, :int32, 7
    optional :definition_json, :string, 8
  end
end

module Riddler
  module Protobuf
    Definition = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.Definition").msgclass
  end
end
