require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task default: :test

desc "Compile protobuf definitions"
task :proto do
  grpc_ruby_plugin = `which grpc_ruby_plugin`.chomp
  command_string = "protoc \
    -I ./lib \
    --ruby_out ./lib \
    --grpc_out ./lib \
    --plugin=protoc-gen-grpc=#{grpc_ruby_plugin} \
    ./lib/riddler/protobuf/*.proto"

  system command_string
end
