# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content_management.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riddler.CreateContentDefinitionRequest" do
    optional :definition_schema_version, :int32, 1
    optional :definition_id, :string, 2
    optional :content_type, :string, 3
    optional :content_id, :string, 4
    optional :version, :int32, 5
    optional :definition, :string, 6
  end
  add_message "riddler.CreateContentDefinitionResponse" do
  end
end

module Riddler
  CreateContentDefinitionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.CreateContentDefinitionRequest").msgclass
  CreateContentDefinitionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.CreateContentDefinitionResponse").msgclass
end
