# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: content_management.proto for package 'riddler'

require 'grpc'
require_relative './content_management_pb'

module Riddler
  module ContentManagement
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'riddler.ContentManagement'

      rpc :CreateContentDefinition, CreateContentDefinitionRequest, CreateContentDefinitionResponse
    end

    Stub = Service.rpc_stub_class
  end
end
